name: webdevhome

services:
  frontend:
    container_name: webdevhome
    build:
      context: .
      target: prod
    ports:
      - "80:80"
  
  dev:
    container_name: webdevhome-dev
    build:
      context: .
      target: dev
      args:
        ls_improvement: true
        rm_cp_mv_interactive: true
        warp: true
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
